### PR TITLE
Update CI configs and add support for Python 3.9

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Comment by ifduyue** [comment]
@illia-v Sorry, I missed this PR.

**Comment by illia-v** [comment]
@ifduyue not a big deal. Thanks for reviewing and merging previous PRs.

Do you think it is possible to release a new version soon? Probably 2.0.0 because of the breaking changes and new features.

Regarding the CI configs, is there a reason for setting exact Python versions in `appveyor.yml` (e.g., `3.9.1` instead of `3.9.x`)?

Also, specifying global `os: Visual Studio 2015` should target the oldest MSVC that can be used for compiling Python 3.6 according to [the table](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F).

**Comment by ifduyue** [comment]
> Do you think it is possible to release a new version soon? Probably 2.0.0 because of the breaking changes and new features.

Let's try 2.0.0.dev0 first. Maybe there will be more changes.

> Regarding the CI configs, is there a reason for setting exact Python versions in `appveyor.yml` (e.g., `3.9.1` instead of `3.9.x`)?

They are from https://github.com/ogrisel/python-appveyor-demo. Since we don't use `run_with_env.cmd` anymore it's safe to remove them.

> Also, specifying global `os: Visual Studio 2015` should target the oldest MSVC that can be used for compiling Python 3.6 according to [the table](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F).

Please send a PR if you'd like to.

**Comment by illia-v** [comment]
> Let's try 2.0.0.dev0 first. Maybe there will be more changes.
@ifduyue done in #108

**Pull request closed without merging**
