### PR TITLE
PyPy support

### LINKED ISSUE #41: PyPy Compatability
I was researching an issue a user reported to andymccurdy/redis-py#708 about some issues with hiredis and PyPy version 4.0.1 (and likely other versions of PyPy).

hiredis-py's feed method isn't able to accept `bytearray` objects running on PyPy. This test (https://github.com/redis/hiredis-py/blob/master/test/reader.py#L168) in hiredis-py's test suite fails running on PyPy testing this exact issue. It produces the following traceback:

```
Traceback (most recent call last):
  File "/Users/andy/hiredis-py/test/reader.py", line 170, in test_feed_bytearray
    self.reader.feed(bytearray(b"+ok\r\n"))
TypeError: must be convertible to a buffer, not bytearray
```

While trying to get hiredis-py's test suite to run on PyPy, I also found two other tests (https://github.com/redis/hiredis-py/blob/master/test/reader.py#L133-L139) that cause the test runner to segfault with the following output:

```
<andy@shockwave: ~hiredis-py (master)> python test.py
.................Fatal error in cpyext, CPython compatibility layer, calling PyList_CheckExact
Either report a bug or consider not using this particular extension
<OpErrFmt object at 0x1074432e0>
RPython traceback:
  File "pypy_module_cpyext_api_2.c", line 21254, in PyPyList_CheckExact
  File "pypy_module_cpyext_pyobject.c", line 2094, in BaseCpyTypedescr_realize
  File "pypy_objspace_std_objspace.c", line 4537, in allocate_instance__W_ObjectObject
  File "pypy_objspace_std_typeobject.c", line 4354, in W_TypeObject_check_user_subclass
Segmentation fault: 11
```

### PR DESCRIPTION
**Pull request by thedrow**
This fixes #41.
It's based on https://github.com/hodgestar/hiredis-cffi and adapted to the current API. Thanks @hodgestar!

What's currently missing:
- [ ] Pass redis-py test suite
- [ ] Benchmark
- [ ] Testing on newer versions of PyPy
- [ ] Test PyPy on Windows?
- [x] Decide if we want to support old versions of PyPy.
  - [x] If we don't I need to convert the old style C -> Python callbacks with the new style callbacks.

### CODE REVIEW

**Comment by thedrow** [comment]
Why isn't Travis running on Pull Requests?

**Comment by badboy** [comment]
I won't pull this in.

I am not a Python developer, nor have I ever even touched PyPy. 
Therefore I simply don't have the time or knowledge to check these quite significant changes.
I agreed to maintain hiredis-py, so to at least be able to fix bugs to either the python adapter or hiredis itself, but I can't develop it any further.

If PyPy does not work with hiredis-py as is (or with minor changes), then this module is simply not compatible.
If the hiredis-cffi fork is maintained by the original author or you (or is simply working stable enough), I'd be happy to link to it though.

**Comment by badboy** [comment]
About Travis: I have no idea.

**Comment by thedrow** [comment]
I'll volunteer to maintain this if needed.
FYI SET key value + GET key benchmarks are: 28206.48 Kops (unless something in the script is really wrong)

**Comment by thedrow** [comment]
I think there's merit in supporting both PyPy and CPython from the same repository.

**Comment by hodgestar** [comment]
@badboy I'm happy to help review this PR (and future PRs) if that would helpful?

**Comment by thedrow** [comment]
@hodgestar Thanks :)
Right now we're 1kOps below the Pure Python parser in PyPy.
Can you see something else that can be improved?

**Comment by hodgestar** [comment]
Since hiredis is parsing strings, it is possible that PyPy with pure Python will just always be faster (the Python + C version always needs to convert back and forth between C strings and Python objects and the JIT can know dynamic information about the current strings that hiredis and the C compile can't).

**Comment by thedrow** [comment]
By Pure Python I mean the Python protocol parser of redis-py running under PyPy.

Actually the main overhead is calling back to Python from C.
If we can do more work in C and get rid of the callbacks it will be as fast if not faster.

**Comment by cirospaciari** [comment]
any change of hiredis support in PyPy using HPy? https://hpyproject.org/

**Pull request closed without merging**
