### PR TITLE
Run tests against Python 3.8

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by michael-k** [comment]
Despite setting `PYTHON_VERSION: "3.8.0"`, appveyor used Python 2.7.
https://ci.appveyor.com/project/duyue/hiredis-py/builds/28350884/job/xbid8ymbjdt08r3y#L8

It looks like they don't support Python 3.8 yet: appveyor/ci#3142

**Comment by ifduyue** [comment]
LGTM

I see there's a workaround from the link you provided above https://github.com/appveyor/ci/issues/3142#issuecomment-546011521, would mind adding it？

**Comment by michael-k** [comment]
I've added the workaround and now Python 3.8 is available:

```
python --version
Python 3.8.0
```

But now the tests are failing:

```
Executing: python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import test
  File "C:\projects\hiredis-py\test\__init__.py", line 11, in <module>
    from . import reader
  File "C:\projects\hiredis-py\test\reader.py", line 3, in <module>
    import hiredis
ImportError: DLL load failed while importing hiredis: The parameter is incorrect.
Command exited with code 1
```

This is probably related to https://bugs.python.org/issue36085 (new in Python 3.8) (see esp. python/cpython#12302).  I'm not familiar with Windows and have no idea how to properly fix this. :(

**Comment by ifduyue** [comment]
I am not familiar with Windows, too. I tried but without success.
However, when I apply these changes in this PR to another project, [it works fine](https://ci.appveyor.com/project/duyue/python-xxhash/builds/28431032/job/j530db1x1192uo7x).
Don't know why..

**Comment by hugovk** [comment]
🚀 Python 3.8 is now available on AppVeyor:

* https://github.com/appveyor/ci/issues/3142#issuecomment-552049896

**Comment by ifduyue** [comment]
Workaround no longed needed. 
ImportError still exists, need to investigate...

**Comment by ifduyue** [comment]
I've found the cause, it's in `test/__init__.py`: 

```
# Add path to hiredis.so load path
path = glob.glob("build/lib*-%s/hiredis" % majorminor)[0]
sys.path.insert(0, path)
```

This somehow makes Python 3.8 on AppVeyor windows raise ImportError.

**Pull request merged**
