### PR TITLE
Enable testing with Python 3.5

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by badboy** [comment]
So, for some reason it does not trigger Travis nor the homu bot. 
Anyway, change seems fine, can you add the same change to `appveyor.yml`?

**Comment by thedrow** [comment]
It fails to compile.

**Comment by badboy** [comment]
I'll check that later

**Comment by thedrow** [comment]
Great. Also let's check why travis isn't running.

**Comment by badboy** [comment]
Fixed in #45

**Pull request closed without merging**
